services:
  postgres:
    image: postgres:17.8
    container_name: candid_pms_postgres
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
